name: Deploy Github Pages

on:
  push:
    branches: ['master']

jobs:
  build-no-base:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: yarn install --production=false
      - run: yarn build
      - run: yarn export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
          external_repository: raelidea/fun
          publish_dir: ./out
          publish_branch: homepage-svr
